# Generated by Django 2.1.2 on 2018-11-04 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('time_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Employee'),
        ),
    ]
