# Generated by Django 2.1.2 on 2019-02-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, help_text='* Only if Job has a static address', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='creator_signature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workday',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
