# Generated by Django 2.1.2 on 2018-11-05 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_sheet', '0002_receipt_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeework',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='employeework',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
