# Generated by Django 2.1.2 on 2019-02-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_sheet', '0002_auto_20190208_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, help_text='* Only if Job always has same address', max_length=150, null=True),
        ),
    ]
