# Generated by Django 2.1.2 on 2018-11-05 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_sheet', '0003_auto_20181105_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeework',
            name='end_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='employeework',
            name='start_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='address',
            field=models.CharField(help_text='**Change if address mobile', max_length=150),
        ),
    ]
