# Generated by Django 2.1.2 on 2018-11-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_sheet', '0004_auto_20181105_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeework',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='employeework',
            name='signature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
