# Generated by Django 2.1.2 on 2019-02-21 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_sheet', '0008_auto_20190217_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeework',
            name='time_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='time_sheet.TimeSheet'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='work_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='time_sheet.WorkDay'),
        ),
    ]
