# Generated by Django 2.1.2 on 2019-03-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_sheet', '0009_auto_20190220_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='creator_signature',
        ),
        migrations.AddField(
            model_name='workday',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
