# Generated by Django 2.1.2 on 2019-03-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_sheet', '0012_auto_20190302_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='date',
            field=models.DateField(),
        ),
    ]
