# Generated by Django 2.1.2 on 2018-10-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_presetauthorizeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presetauthorizeduser',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
