# Generated by Django 2.1.2 on 2018-10-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181027_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pin',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
